package com.example.erp.department.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Payload for {@code POST /api/departments}.
 * <p>
 * The id is generated by the database, so it is deliberately absent. {@code description} is the
 * only optional field; the schema has both {@code name} and {@code department_code} as NOT NULL
 * and unique.
 */
public record DepartmentCreateRequest(
                @NotBlank @Size(max = 255) String name,
                @Size(max = 255) String description,
                @NotBlank @Size(max = 255) String departmentCode) {
}
