package com.example.erp.job.dto;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

/**
 * Payload for {@code POST /api/jobs}.
 * <p>
 * The id is generated by the database, so it is deliberately absent. A NOT NULL boolean falls
 * back to false when omitted rather than being rejected.
 */
public record JobCreateRequest(
        @NotNull Long legalEntityIdId,
        @NotBlank @Size(max = 32) String jobCode,
        @NotBlank @Size(max = 120) String jobName,
        @NotBlank @Size(max = 16) String jobStatus,
        @NotBlank @Size(max = 32) String referenceQuality,
        @NotBlank @Size(max = 32) String source,
        @NotNull @Min(0) Integer createdBy,
        @Min(0) Integer updatedBy) {
}
