spring.application.name=liquibase

spring.datasource.url=jdbc:mysql://172.17.0.1:3306/erp?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=TvWS7iUUbVhlG85rO4On9zja
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yaml