package com.example.erp.organization.dto;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import java.time.LocalDate;

/**
 * Payload for {@code POST /api/organizations}.
 * <p>
 * The id is generated by the database, so it is deliberately absent. The two flags the schema
 * declares NOT NULL default to false when omitted rather than being rejected, since a caller
 * creating its first organization has no reason to care about them.
 */
public record OrganizationCreateRequest(
        @NotBlank @Size(max = 255) String name,
        Boolean logoUploaded,
        Boolean defaultOrg,
        @Size(max = 100) String userRole,
        LocalDate accountCreatedDate,
        @Size(max = 50) String timeZone,
        @Size(max = 10) String languageCode,
        @Size(max = 50) String dateFormat,
        @Size(max = 10) String fieldSeparator,
        @Min(1) @Max(12) Integer fiscalYearStartMonth,
        Boolean taxGroupEnabled,
        @Size(max = 50) String userStatus,
        @Size(max = 255) String contactName,
        @Size(max = 100) String industryType) {
}
