package com.example.erp.designation.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * Payload for {@code POST /api/designations}.
 * <p>
 * The id is generated by the database, so it is deliberately absent. A NOT NULL boolean falls
 * back to false when omitted rather than being rejected.
 */
public record DesignationCreateRequest(
        @NotBlank @Size(max = 255) String name) {
}
